blank_issues_enabled: false
contact_links:
  - name: "\U0001F680 Feature Request"
    about: "Suggest a new feature to make Nx better"
    url: https://github.com/nrwl/nx/discussions/new?category=feature-requests
  - name: Start a Discussion
    about: "Start a discussion to share your experience with Nx"
    url: https://github.com/nrwl/nx/discussions/new/choose
  - name: Join the Discord
    url: https://go.nx.dev/community
    about: "The Nx Official Discord Server is a great place for questions to be asked and answered. Please use the #forum if you need help with your workspace!"
  - name: Are you looking for integration with a new tool?
    url: https://nx.dev/community
    about: "There are a lot of awesome Plugins for Nx provided by the community! Check here to see if there is a community plugin to integrate your tool."
  - name: Read the community guidelines
    about: "Please make sure you have read the submission guidelines before posting an issue"
    url: https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-an-issue
